//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickeningSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatStatus
    {
        public int Id { get; set; }
        public int StatusId { get; set; }
        public int SeatId { get; set; }
        public int ScreeningId { get; set; }
        public decimal Price { get; set; }
        public string phoneNumber { get; set; }
    
        public virtual Screening Screening { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Status Status { get; set; }
    }
}
